###
POST http://localhost:8080/register
Accept: application/json
Content-Type: application/json

{
    "username":"tami",
    "email": "test@mail.com",
    "password": "password"
}


###
POST http://localhost:8080/login
Accept: application/json
Content-Type: application/json

{
    "email": "test@mail.com",
    "password": "password"
}


